version: '3.8'

services:
  antmedia:
    build: .
    container_name: antmedia
    network_mode: host # Recommended for WebRTC performance
    restart: always
    volumes:
      - ./ams_data:/usr/local/antmedia/webapps
      - ./ams_logs:/usr/local/antmedia/log
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
